services:
  mysql:
    image: 'mysql:latest'
    container_name: school-mysql
    environment:
      - 'MYSQL_DATABASE=school_management'
      - 'MYSQL_ROOT_PASSWORD=123456'
      - 'TZ=Asia/Shanghai'
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - '3306'
  redis:
    image: 'redis:latest'
    container_name: school-redis
    command: redis-server --requirepass 123456 --appendonly yes
    volumes:
      - redis-data:/data
    ports:
      - '6379:6379'
volumes:
  mysql-data:
    driver: local
  redis-data:
    driver: local
  nacos-data:
    driver: local
  nacos-logs:
    driver: local
